// stepsData.js

const stepsData = [
  {
    id: 1,
    totalSteps: 5094,
    caloriesBurnt: 200,
    distanceTraveled: '3 km',
    timeTaken: '30 mins',
    oxygenPercentage: '95%',
  },
  {
    id: 2,
    totalSteps: 8657,
    caloriesBurnt: 300,
    distanceTraveled: '5 km',
    timeTaken: '45 mins',
    oxygenPercentage: '97%',
  },
  {
    id: 3,
    totalSteps: 12675,
    caloriesBurnt: 500,
    distanceTraveled: '8 km',
    timeTaken: '1 hour',
    oxygenPercentage: '98%',
  },
  {
    id: 4,
    totalSteps: 15409,
    caloriesBurnt: 600,
    distanceTraveled: '10 km',
    timeTaken: '1 hour 15 mins',
    oxygenPercentage: '99%',
  },
  {
    id: 5,
    totalSteps: 2087,
    caloriesBurnt: 100,
    distanceTraveled: '1.5 km',
    timeTaken: '15 mins',
    oxygenPercentage: '94%',
  },
  {
    id: 6,
    totalSteps: 18453,
    caloriesBurnt: 720,
    distanceTraveled: '12 km',
    timeTaken: '1 hour 40 mins',
    oxygenPercentage: '96%',
  },
  {
    id: 7,
    totalSteps: 25236,
    caloriesBurnt: 1000,
    distanceTraveled: '15 km',
    timeTaken: '2 hours',
    oxygenPercentage: '97%',
  },
  {
    id: 8,
    totalSteps: 11469,
    caloriesBurnt: 450,
    distanceTraveled: '7 km',
    timeTaken: '50 mins',
    oxygenPercentage: '95%',
  },
  {
    id: 9,
    totalSteps: 3224,
    caloriesBurnt: 150,
    distanceTraveled: '2 km',
    timeTaken: '20 mins',
    oxygenPercentage: '92%',
  },
  {
    id: 10,
    totalSteps: 7658,
    caloriesBurnt: 280,
    distanceTraveled: '4.5 km',
    timeTaken: '35 mins',
    oxygenPercentage: '96%',
  },
];

export default stepsData;
